### ISSUE TITLE
unittest `test_export.py` fails to find and read the provided csv file

### ISSUE THREAD

**Issue by max-hassani** [pyiron/pyiron_base#125]
In the branch `export_import_archive`, for testing the export functionality, I compare the produced csv file during the test with a provided csv file in the directory. But the tests fails to find the file. Since the test does not fail on my machine, I wonder what is the reason? I change the relative path to the absolute path, I thought it might be the issue, but it did not help. If someone has an idea on how to solve this issue, I would be grateful.

**Comment by jan-janssen** [comment]
The issue is where you execute the tests, in the continuous integration environment we execute them at the root of the repository: 
https://github.com/pyiron/pyiron_base/blob/master/.github/workflows/unittests.yml#L35

While many IDEs execute the tests in the corresponding folder in your case `tests/archiving`. 

To address this we typically get the file location relative to the script that is executed: 
https://github.com/pyiron/pyiron_base/blob/master/tests/job/test_script.py

Rather than using `os.getcwd()`

**Comment by max-hassani** [comment]
> 
> 
> The issue is where you execute the tests, in the continuous integration environment we execute them at the root of the repository:
> https://github.com/pyiron/pyiron_base/blob/master/.github/workflows/unittests.yml#L35
> 
> While many IDEs execute the tests in the corresponding folder in your case `tests/archiving`.
> 
> To address this we typically get the file location relative to the script that is executed:
> https://github.com/pyiron/pyiron_base/blob/master/tests/job/test_script.py
> 
> Rather than using `os.getcwd()`

Thanks a lot, @jan-janssen. I missed it in the error :(
 So I will follow the way, the path is given in the `test_script.py`.
