### ISSUE TITLE
super() and __init__() - old and new mix 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_base#196]
Currently we have a mix of both, the old:

```
super(Class, self).function()
```

And the new python 3

```
super().function()
```

I guess we should update them all to follow the new format. The tricky part are the cases with multiple inheritance. 

In the same way we still have classes derived from `objects`. 

@muh-hassani and @niklassiemer Can one of you take a look at this?

**Comment by niklassiemer** [comment]
I may have a look. However, this is not urgent and we will probably end up re-writing some classes entirely using a new input/output object. Therefore, I am not sure how much benefit would be gained by these more cosmetic changes. In the end, it is the same `super` call, just python3 learned to treat `()` as `(self.__class__, self)` by default.

And I do not think that having a different code style for special cases is a problem. In the cases where we need other arguments since the standard MRO is not the one we need, I am actually in favor of having a different style, probably alongside with a comment why we need it this way.
