### ISSUE TITLE
data_dict not found

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#44]
The following job doesn't work (anymore). It's certainly related to the change from `GenericParameters` to `InputList`, but I don't know how it should look now.

submitter.ipynb:
```
from pyiron import Project

pr = Project('JOB')

job = pr.create_job('ScriptJob', 'job')
job.input['value'] = 300
job.script_path = 'job.ipynb'
job.run()
```

job.ipynb:
```
from pyiron import Notebook as nb
coeff_tot = nb.get_custom_dict()
print(coeff_tot['value'])`
```

**Comment by pmrv** [comment]
The problem is here
https://github.com/pyiron/pyiron_base/blob/909b815f7cd4b7a952be64367ac1c93037ee1049/pyiron_base/job/external.py#L43
where the Notebook class parses the job hdf manually.  Since the HDF changed with InputList this fails.  Is this `Notebook.get_custom_dict()` supposed to work for ScriptJobs only or is this a more general mechanism?

I am very reluctant to allow any other function poke around in the HDF internals of jobs, as I consider those implementation details.  Maybe I could add a similar method to the ScriptJob.

**Comment by samwaseda** [comment]
> The problem is here
> 
> https://github.com/pyiron/pyiron_base/blob/909b815f7cd4b7a952be64367ac1c93037ee1049/pyiron_base/job/external.py#L43
> 
> 
> where the Notebook class parses the job hdf manually. Since the HDF changed with InputList this fails. Is this `Notebook.get_custom_dict()` supposed to work for ScriptJobs only or is this a more general mechanism?
> I am very reluctant to allow any other function poke around in the HDF internals of jobs, as I consider those implementation details. Maybe I could add a similar method to the ScriptJob.

I'm fine with anything. It's just I can't launch simulations right now because of this, which is causing a lot of trouble to me.

**Comment by jan-janssen** [comment]
Thx @samwaseda for fixing this, we had unit tests to check for this but they have been removed in the last pull request https://github.com/pyiron/pyiron_base/pull/34 so I guess we still need to improve the reviewing of the pull requests.
