### ISSUE TITLE
Changed behavior: Current path not included in `project_paths`

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_base#538]
Right now quite some of out CI are failing (atomistics Notebooks, integration tests for contrib was failing before) since we did not properly set up the `.pyiron` configuration. 
```python
ValueError: the current path /home/runner/work/pyiron_atomistics/pyiron_atomistics/tip3p_water/ is not included in the .pyiron configuration 'project_paths': []
```
Before our state updates, we must have had something like `project_check_enable = False if project_paths = []` or the like.

**Comment by liamhuber** [comment]
Gah. Very likely my fault. Checking the diff in my last couple PRs focusing on the default values for Settings._config and the behavior of DatabaseManager.top_path are the prime suspects. Because of vacation the absolute earliest I could look at it is late tonight, so if you're willing to take a look in those places first I hope you can get a quick solution without me

**Comment by liamhuber** [comment]
I had a quiet moment to go back and look over #486 and #519. Unfortunately I don't see anything in either of the two places I mentioned that should be causing this. I'm at a loss where the behaviour change came from -- did you guys figure it out in the meeting today?

**Comment by niklassiemer** [comment]
Not in the meeting but it is exactly the awful `else` we discuss in https://github.com/pyiron/pyiron_base/pull/541
