### ISSUE TITLE
FlattenedStorage.extend broken for dtype != {int,float}

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#764]
`extend` only works when default fill are defined for all arrays. Since they are given by default only for int and float this breaks for all other dtypes.

**Comment by Leimeroth** [comment]
This was intended to prevent undefined behaviour. If we want to avoid this we should probably add default values for more dtypes, but I think an error is still better than an array partly filled with random bits. I tried to throw a helpful error in [github.com/pyiron/pyiron_base/](https://github.com/pyiron/pyiron_base/blob/3e081cba2d0742ee9771bf03eb131b0358b405dc/pyiron_base/generic/flattenedstorage.py#L965)

**Comment by Leimeroth** [comment]
More dyptes are added in #765

**Comment by Leimeroth** [comment]
IMO this solution is fine, so I will close this.

**Comment by pmrv** [comment]
I think a slightly cleaner way would be to just resize the storages before combining them -> no uninitialized array, but I won't get around to it for a while.

**Comment by Leimeroth** [comment]
The problem of uninitialized  arrays occurs when other contains an array that is not present in self.
I don't think resizing can help here, because the array will be added with combined length to keep indexing consistent, but there have to be some fill values or it will be uninitialized, i.e. undefined behavior.
```
            if k not in self._per_chunk_arrays.keys():
                dtype, fill = get_dtype_and_fill(storage=other, name=k)
                self.add_array(
                    name=k, dtype=dtype, shape=a.shape[1:], fill=fill, per="chunk"
                )
```


When calling extend the uninitialized  part of self is overwritten with other by using self.num_chunks and self.num_elements instead of self._num_chunks_alloc and self._num_elements_alloc , and resizing is done when necessary:
```
        if combined_num_chunks > self._num_chunks_alloc:
            self._resize_chunks(combined_num_chunks)
        if combined_num_elements > self._num_elements_alloc:
            self._resize_elements(combined_num_elements)
```

**Comment by Leimeroth** [comment]
Generally allowing arrays without fill values could lead to undefined behavior, so the completely clean way would probably be to make fill values mandatory
